#!/usr/bin/env bash

set -x

init_neovim() (
    echo "Initializing neovim setup"

    for py_major in {2,3}; do
        if [ ! -d "${PYENV_ROOT}/versions/neovim${py_major}" ]; then
            pyenv virtualenv "$(pyenv latest --print ${py_major})" "neovim${py_major}"
        else
            echo "${PYENV_ROOT}/versions/neovim${py_major} venv already exists"
        fi
        "${PYENV_ROOT}/versions/neovim${py_major}/bin/pip" install -r ./neovim-requirements.txt
    done

    if command -v npm >/dev/null 2>&1; then
        npm install -g neovim typescript prettier
    fi

    pyenv rehash
    nodenv rehash
)

post_init_python_system () (
    for py_major in {2,3}; do
        echo "Installing packages for major python release ${py_major}"
        "$(pyenv root)/versions/$(pyenv latest --print $py_major)/bin/pip" install -r "${PWD}/python-system-requirements.txt"
    done
)

(
    "${PWD}/dependencies/fzf/install" --all --no-bash --no-fish --64;
    "${PWD}/dependencies/nerd-fonts/install.sh" Hack;
    post_init_python_system ;
    init_neovim
)

set +x
