#!/bin/bash

install_system_packages() {
    sudo apt install -yy -qq \
        dconf-cli \
        zsh \
        ccache \
        tree
}

# pull all submodules
git submodule update --init --recursive

# install all necessary system packages
(sudo apt update -qq ; install_system_packages)

# create a target directory of bins coming mainly from my dotfiles
mkdir -p $HOME/.local/bin
