#!/bin/bash

install_system_packages() {
    sudo apt install -yy -qq \
        dconf-cli \
        zsh \
        ccache \
        tree \
        silversearcher-ag
}

install_ctags() {
    # drop unused package
    sudo apt remove exuberant-ctags -qq -yy

    local shouldInstall=0
    if command -v ctags >/dev/null 2>&1; then
        # already installed check if need to reinstall
        cd ./dependencies/ctags
        git fetch origin
        if [[ $(git log HEAD..origin/master --oneline | wc -l) -ne 0 ]]; then
            (tput setaf 1 ; echo "dependencies/ctags is outdated, update the module first")
            exit 1
        else
            shouldInstall=1
        fi
        cd -
    else
        shouldInstall=1
    fi

    if [ $shouldInstall -eq 1 ]; then
        cd ./dependencies/ctags

        ./autogen.sh
        ./configure --prefix=$HOME/.local
        make
        make install

        cd -
    fi
}

# install all necessary system packages
(sudo apt update -qq ; install_system_packages)

# create a target directory of bins coming mainly from my dotfiles
mkdir -p $HOME/.local/bin
