#!/usr/bin/env bash

install_ctags() {
    # drop unused package
    sudo aptitude purge exuberant-ctags -q -y

    local shouldInstall=0
    if command -v ctags >/dev/null 2>&1; then
        # already installed check if need to reinstall
        cd ./dependencies/ctags || echo "ctags submodule not fetched"
        git fetch origin
        if [[ $(git log HEAD..origin/master --oneline | wc -l) -ne 0 ]]; then
            (tput setaf 1 ; echo "dependencies/ctags is outdated, update the module first")
            exit 1
        else
            shouldInstall=1
        fi
        cd - || exit 1
    else
        shouldInstall=1
    fi

    if [ $shouldInstall -eq 1 ]; then
        cd ./dependencies/ctags || echo "ctags submodule not fetched"

        ./autogen.sh
        ./configure --prefix="${HOME}/.local"
        make
        make install

        cd - || exit 1
    fi
}

# install all necessary system packages
(
    sudo aptitude update -q ;
    install_ctags ;
)
