#!/bin/zsh

# Loaded before zshrc

export ZDOTDIR="${HOME}"
export K_DOTFILES_DIR="${HOME}/.dotfiles"
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-~/.cache}
export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
export GOENV_ROOT="${K_DOTFILES_DIR}/dependencies/goenv"

export PYENV_ROOT="${HOME}/.pyenv"
export GOENV_ROOT="${HOME}/.goenv"
export NODENV_ROOT="${HOME}/.nodenv"
export JENV_ROOT="${HOME}/.jenv"

export TERM="xterm-256color"
export PAGER='less'

if >/dev/null 2>&1 command -v nvim ; then
  export EDITOR=nvim
  nvim -es +'exe !has("nvim-0.3.2")."cq"' && export MANPAGER="nvim +Man!"
elif >/dev/null 2>&1 command -v vim ; then
  export EDITOR=vim
else
  export EDITOR=vi
fi
export VISUAL="${EDITOR}"

# Python variables
export PYTHONIOENCODING='UTF-8'             # make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONUTF8=1                         # ---/---
export PYTHONDONTWRITEBYTECODE=1            # prevent Python from making .pyc files that may become stale and cause weird bugs

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $HOME/.local/bin
  $PYENV_ROOT/bin
  $NODENV_ROOT/bin
  $GOENV_ROOT/bin
  $JENV_ROOT/bin
  $K_DOTFILES_DIR/dotbot/bin
  $path
)
[ $commands[gem] ] && {
    path=(
        "$(gem environment | grep 'USER INSTALLATION DIRECTORY' | awk -F': ' '{print $2}')/bin"
        $path
    )
}

[ $commands[pyenv] ] && {
    eval "$(pyenv init --path)"
}
[ $commands[rbenv] ] && {
    eval "$(rbenv init -)"
}

# hide % at end of output
export PROMPT_EOL_MARK=''

# Less

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# pure theme settings
export PURE_GIT_PULL=1

# use buildkit for docker
export DOCKER_BUILDKIT=1

# aliases
[ $commands[nvim] ] && {
    # overwrite vim
    alias nvim="nvim -u ~/.config/nvim/init.lua"
    alias ovim="nvim -i ~/.config/nvim/init.nvim"
    alias vi='nvim';
    alias vim='nvim';
    alias view='nvim -R';
}
