#!/bin/zsh

# If you come from bash you might have to change your $PATH.

export ZDOTDIR=~
export TERM="xterm-256color"
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}

# load all necessary completion and init stuff
[ -f ~/.zgen/zgen.zsh ] && source ~/.zgen/zgen.zsh
[ -f ~/.zprezto/init.zsh ] && source ~/.zprezto/init.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.fzf.settings ] && source ~/.fzf.settings
[ -f ~/.npmrc.sh ] && source ~/.npmrc.sh
[ -f ~/.t.sh ] && source ~/.t.sh

[ $commands[kubectl] ] && source <(kubectl completion zsh)

# load local customizations
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

if ! zgen saved; then
    zgen prezto
    zgen load sobolevn/wakatime-zsh-plugin
    zgen save
fi
