# If you come from bash you might have to change your $PATH.

export ZDOTDIR=$HOME
export TERM="xterm-256color"
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

# load all necessary completion and init stuff
[ -f $HOME/.zgen/zgen.zsh ] && source $HOME/.zgen/zgen.zsh
[ -f $HOME/.zprezto/init.zsh ] && source $HOME/.zprezto/init.zsh
[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh
[ -f $HOME/.fzf.settings ] && source $HOME/.fzf.settings
[ -f $HOME/.npmrc.sh ] && source $HOME/.npmrc.sh
[ -f $HOME/.t.sh ] && source $HOME/.t.sh

[ $commands[kubectl] ] && source <(kubectl completion zsh)

# load local customizations
[ -f $HOME/.zshrc.local ] && source $HOME/.zshrc.local

if ! zgen saved; then
    zgen prezto
    zgen load sobolevn/wakatime-zsh-plugin
    zgen save
fi

