#!/bin/zsh

setopt promptsubst

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=6'
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# settings for prezto imported stuff
zstyle ':prezto:*:*' color 'yes'
zstyle ':prezto:*:*' case-sensitive 'false'

zstyle ':prezto:module:utility' correct 'yes'
zstyle ':prezto:module:utility' safe-ops 'yes'
zstyle ':prezto:module:utility:ls' dirs-first 'yes'

zstyle ':prezto:module:ssh:load' identities 'github'
zstyle ':prezto:module:completion:*:hosts' etc-host-ignores '0.0.0.0' '127.0.0.1'

zstyle ':prezto:module:editor' key-bindings 'emacs'
zstyle ':prezto:module:editor' dot-expansion 'yes'
zstyle ':prezto:module:editor' ps-context 'yes'

source ~/.zplugin/zplugin.zsh

# prompt
zplugin ice \
    pick"async.zsh" \
    src"pure.zsh" \
    atload'source ~/.dotfiles/zsh/prompt.zsh'
zplugin light sindresorhus/pure

# plugins of all sorts
zplugin load zdharma/zsh-unique-id
zplugin ice wait lucid ; zplugin light zdharma/z-p-submods
zplugin ice wait lucid ; zplugin light sobolevn/wakatime-zsh-plugin
zplugin ice wait lucid ; zplugin light RobSis/zsh-reentry-hook
zplugin ice wait'1' lucid ; zplugin light hlissner/zsh-autopair
zplugin ice wait'1' lucid ; zplugin light djui/alias-tips
zplugin ice wait'1' lucid ; zplugin load voronkovich/gitignore.plugin.zsh
zplugin ice wait'1' as'program' pick'bin/git-dsf' lucid ; zplugin light zdharma/zsh-diff-so-fancy
zplugin ice wait'1' lucid pick"h.sh" ; zplugin light paoloantinori/hhighlighter

# jq
zplugin ice from'gh-r' \
    as'command' \
    mv'jq* -> jq' \
    bpick'*linux*'
zplugin load stedolan/jq

# autojump
zplugin ice \
    wait'2' \
    lucid \
    as'command' \
    pick'fasd' \
    atpull'!git reseti --hard' \
    atload'source ~/.dotfiles/zsh/fasd.zsh'
zplugin load clvv/fasd

# dircolors
zplugin ice wait"0c" lucid reset \
    atclone"local P=${${(M)OSTYPE:#*darwin*}:+g}
            \${P}sed -i \
            '/DIR/c\DIR 38;5;63;1' LS_COLORS; \
            \${P}dircolors -b LS_COLORS > c.zsh" \
    atpull'%atclone ; !git reset --hard' pick"c.zsh" nocompile'!' \
    atload'zstyle ":completion:*" list-colors “${(s.:.)LS_COLORS}”'
zplugin light trapd00r/LS_COLORS

# direnv
zplugin ice \
    as'program' \
    atclone'./direnv hook zsh > zhook.zsh' \
    atpull'%atclone'\
    pick'direnv' \
    src'zhook.zsh' \
    make'!'
zplugin light direnv/direnv

# git extra stuff
zplugin ice wait lucid \
    as'program' \
    pick'$ZPFX/bin/git-*' \
    make'PREFIX=$ZPFX' \
    nocompile
zplugin light tj/git-extras

zplugin ice svn silent ; zplugin snippet PZT::modules/environment
zplugin ice svn silent ; zplugin snippet PZT::modules/terminal
zplugin ice svn silent ; zplugin snippet PZT::modules/editor
zplugin ice svn silent ; zplugin snippet PZT::modules/history
zplugin ice svn silent ; zplugin snippet PZT::modules/directory
zplugin ice svn silent ; zplugin snippet PZT::modules/utility
zplugin ice svn silent ; zplugin snippet PZT::modules/helper
zplugin ice svn silent ; zplugin snippet PZT::modules/gpg
zplugin ice svn silent ; zplugin snippet PZT::modules/ssh
zplugin ice svn silent ; zplugin snippet PZT::modules/git
zplugin ice svn silent ; zplugin snippet PZT::modules/docker
zplugin ice svn silent lucid ; zplugin snippet PZT::modules/archive

# autosuggestions, syntax-highlighting & history searching
zplugin ice \
    wait \
    lucid \
    blockf \
    atpull'zplugin creinstall -q .' \
    atload'source ~/.dotfiles/zsh/comp.zsh'
zplugin load zsh-users/zsh-completions

zplugin ice \
    wait \
    lucid \
    atinit'ZPLGM[COMPINIT_OPTS]=-C; zpcompinit; zpcdreplay'
zplugin load zdharma/fast-syntax-highlighting

zplugin ice \
    wait \
    lucid \
    atload'!_zsh_autosuggest_start' \
    wrap-track'_zsh_autosuggest_start'
zplugin load zsh-users/zsh-autosuggestions

zplugin ice \
    wait'1' \
    lucid \
    atload'source ~/.dotfiles/zsh/history.zsh'
zplugin load zsh-users/zsh-history-substring-search

[ $commands[pyenv] ] && {
    eval "$(pyenv init - --no-rehash zsh)"
    eval "$(pyenv virtualenv-init -)"
}
[ $commands[nodenv] ] && {
    eval "$(nodenv init - --no-rehash zsh)"
}
[ $commands[goenv] ] && {
    eval "$(goenv init - --no-rehash zsh)"
    path=(
        $GOROOT/bin
        $GOPATH/bin
        $path
    )
    export GOBIN="$GOPATH/bin";
}
[ $commands[kubectl] ] && source <(kubectl completion zsh)

[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
source ~/.fzf.zsh
source ~/.fzf.settings
source ~/.npmrc.sh

zplugin ice wait lucid ; zplugin load 'wfxr/forgit'
