#!/usr/bin/env bash

# taken from https://github.com/rafi/vim-tagabana

set -e

dry_run() {
    ctags "$@"
    exit $?
}

for arg in "$@"; do
    case "$arg" in
        --help|--version|--license) dry_run "$@";;
        --list*) dry_run "$@";;
    esac
done

# Find git repository's top-level directory
cwd=$(git rev-parse --show-toplevel || pwd)
if [ -z "$cwd" ]; then
    ctags "$@"
    exit $?
fi
pushd "$cwd" 1>/dev/null

# Hash the top-level directory path
if [ "${#cwd}" -lt 150 ]; then
    # Just replacing directory separators if path is
    # less than 150 characters.
    hash=${cwd//\//=+}
    hash=${hash//\\/=+}
    hash=${hash//\:/=-}
elif hash sha256sum 2>/dev/null; then
    # Use SHA256 for long paths
    hash=$(printf "%s" "$cwd" | sha256sum | sed 's/\s\+\-.*$//g')
else
    # Simple hash when sha256sum isn't available
    sum=0
    for i in $(seq 0 ${#cwd}); do
        char=${cwd:${i}:1}
        dec=$(printf '%d\n' "'$char")
        ((sum+=dec*(i+1)))
    done
    hash=$(printf "%x\n" ${sum})
fi

if [ -z "$hash" ]; then
    echo "[ctags] Error while creating tags: Empty hash"
    exit 2
fi

# Generate the tags file into the central repository
cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/vim/tags"
mkdir -p "${cache_dir}"
filepath="${cache_dir}/${hash}"
trap 'rm -f "${filepath}.$$"' EXIT

# Run ctags, store exit code.
# On complete move from temp name.
ctags -f"${filepath}.$$" "$@"
exit_code=$?

mv "${filepath}.$$" "${filepath}"
popd 1>/dev/null
exit $exit_code
