#!/usr/bin/env bash

# inspired by https://github.com/git-hook/post-clone/blob/master/hooks/post-checkout

declare repo
repo=$(git rev-parse --show-toplevel)

_maintenance() {
    test "$(git config maintenance.auto)" = "true" && git maintenance start
}

_submodules() {
    git submodule update \
        --recursive \
        --init \
        --checkout \
        --recommend-shallow \
        --force \
        --jobs 4 \
        --progress
}

_main() {
    local flag="${3:-0}"
    # only run on branch checkouts, not file checkouts (restore/unstage)
    [[ "$flag" != "1" ]] && return 0

    echo "post-checkout [start][${repo}]"
    _submodules
    _maintenance
    echo "post-checkout [done][${repo}]"
}

_main "$@"
