---
name: Automerge

"on":
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  Please:
    runs-on: ubuntu-20.04
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_REMOVE_LABELS: automerge
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: true
          MERGE_RETRY_SLEEP: 100000
          MERGE_RETRIES: 20
